### ISSUE TITLE
hiera-consul on Puppet Forge

### ISSUE THREAD

**Issue by madAndroid** [jsok/hiera-consul#1]
Hi,

Although they have the exact same name, this repo appears to differ from the puppet module on the forge - are there any major differences in the code and functionality? It would be great if the two could be merged at some point, as we've installed from rubygems, expecting the functionality to be the same, but it appears as if they've diverged at some point.

**Comment by jsok** [comment]
Hi @madAndroid yes this is different and from lynxman/hiera-consul.

My needs were slightly different and it was a bit of a learning experience too.
I haven't considered merging the two projects, but would be open to it.

The major differences AFAIK are around hash merging. This gem doesn't yet support SSL/TLS, however it would be trivial to add.

**Comment by madAndroid** [comment]
Ah, okay .. yes, I think it would be beneficial: to reduce confusion, and have consistency between the gem and the puppet module - I'm willing to take on that work, if you're open to that as well?

> The major differences AFAIK are around hash merging. This gem doesn't yet support SSL/TLS, however it would be trivial to add.

`lynxman/hiera-consul` already has SSL support, so it would be a matter of adding the hash merge changes you've implemented. I'm considering implementing these as a `hiera_hash` call. This would persist the current behaviour of `lynxman/hiera-consul`, but still provide hash merging functionality.
